[Display]
WindowWidth=1280
WindowHeight=720
WindowName=FlowEngine
FullScreen=0

[Network]
DefaultPort=7777
MaxPlayers=4

[Input]
; Format -> ContextName.ActionName=HardwareKey

; --- Gameplay Context (Platformer Controls) ---
Gameplay.P1_LEFT=A
Gameplay.P1_RIGHT=D
Gameplay.P1_JUMP=Space

; --- UI Menu Context (For pausing the game) ---
Menu.UI_UP=W
Menu.UI_DOWN=S
Menu.UI_SELECT=Enter
Menu.UI_CANCEL=Escape